import os
import json
import time
import requests
import pandas as pd
import random
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import streamlit as st


from google_play_scraper import search, app ,reviews
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
def update_search_history(new_term):
    """
    Updates the search history stored in the Streamlit session state.

    This function ensures that the search history is maintained as a list of unique
    search terms, with the most recent term added to the beginning of the list.
    The history is limited to the 10 most recent terms.

    Args:
        new_term (str): The new search term to add to the history.

    Notes:
        - If the session state does not already contain a search history, it initializes it.
        - Duplicate terms are not added to the history.
    """
  
    if "search_history" not in st.session_state:
        st.session_state.search_history = []
    if new_term and new_term not in st.session_state.search_history:
        st.session_state.search_history.insert(0, new_term)
        st.session_state.search_history = st.session_state.search_history[:10] # Limit to 10 items

### 🔁 Fonction Générique de Cache
def get_cached_or_fresh_data(search_term, search_function, cache_dir="cache", **kwargs):
    """
    Retrieves data either from a local cache or by performing an online search.
    This function checks if the requested data is already cached in a JSON file. 
    If the cache exists, it loads the data from the file. Otherwise, it performs 
    an online search using the provided search function, saves the result to the 
    cache, and returns the data.
    Args:
        search_term (str): The term to search for, used to generate the cache filename.
        search_function (callable): A function that performs the search and returns 
            the data as a DataFrame or similar structure.
        cache_dir (str, optional): The directory where cached files are stored. 
            Defaults to "cache".
        **kwargs: Additional keyword arguments to pass to the search function.
    Returns:
        pd.DataFrame: A DataFrame containing the retrieved data, either from the 
        cache or from the online search.
    Notes:
        - The cache filename is generated by replacing spaces in the search term 
          with underscores and appending the search function's name.
        - The data is cached in JSON format with UTF-8 encoding.
        - If the cache directory does not exist, it will be created automatically.
   
    """
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)
    safe_term = search_term.replace(" ", "_").lower()
    json_path = os.path.join(cache_dir, f"{safe_term}{search_function.__name__}.json")

    if os.path.exists(json_path):
        print(f"🔁 Chargement du cache pour '{search_term}' ({search_function.__name__})")
        with open(json_path, "r", encoding="utf-8") as f:
            return pd.DataFrame(json.load(f))
    else:
        print(f"🆕 Recherche en ligne pour '{search_term}' ({search_function.__name__})")
        df = search_function(search_term, **kwargs)
        df.to_json(json_path, orient="records", indent=4, force_ascii=False)
        return pd.DataFrame(df)


### 📱 Google Play Store (Scraper API)
def search_google_play_apps(search_term, lang="en", country="us", n_hits=10):
    """
    Searches for apps on the Google Play Store and retrieves detailed information about each app.
    
    Args:
        search_term (str): The term to search for on the Google Play Store.
        lang (str, optional): The language to use for the search. Defaults to "en".
        country (str, optional): The country to use for the search. Defaults to "us".
        n_hits (int, optional): The number of search results to retrieve. Defaults to 10.
    
    Returns:
        pd.DataFrame: A DataFrame containing detailed information about the apps, including:
            - title: The app's title.
            - appId: The app's unique identifier on the Google Play Store.
            - description: A brief description of the app.
            - installs: The number of installs of the app.
            - score: The app's average rating score.
            - ratings: The total number of ratings for the app.
            - genre: The genre/category of the app.
            - developer: The name of the app's developer.
            - free: Whether the app is free or not.
            - url: The URL to the app's page on the Google Play Store.
    
    Notes:
        - This function uses the google_play_scraper library to perform the search and retrieve app details.
        - If an error occurs while retrieving details for a specific app, it will be skipped, and an error message will be printed.
    """
    search_results = search(search_term, lang=lang, country=country, n_hits=n_hits)
    apps_data = []

    for result in search_results:
        try:
            app_data = app(result["appId"])
            apps_data.append({
                "title": app_data.get("title"),
                "appId": app_data.get("appId"),
                "description": app_data.get("description"),
                "installs": app_data.get("installs"),
                "score": app_data.get("score"),
                "ratings": app_data.get("ratings"),
                "genre": app_data.get("genre"),
                "developer": app_data.get("developer"),
                "free": app_data.get("free"),
                "url": app_data.get("url")
            })
        except Exception as e:
            print(f"Erreur {result['appId']}: {e}")
    return pd.DataFrame(apps_data)

def search_google_play_apps_cached(search_term, lang="en", country="us", n_hits=10):
    """
    Searches for apps on Google Play with caching support.

    This function retrieves a list of apps from Google Play based on the given search term.
    It first checks if cached data is available for the search term. If not, it fetches fresh
    data using the search_google_play_apps function and caches the result for future use.

    Args:
        search_term (str): The term to search for on Google Play.
        lang (str, optional): The language code for the search (default is "en").
        country (str, optional): The country code for the search (default is "us").
        n_hits (int, optional): The maximum number of search results to return (default is 10).

    Returns:
        list: A list of search results, either from the cache or freshly fetched.
    """
    return get_cached_or_fresh_data(search_term, search_google_play_apps, lang=lang, country=country, n_hits=n_hits)


### 💬 Product Hunt (via Selenium)
def stars(button):
    try:
        filled = 0
        half = 0
        stars = button.find_elements(By.TAG_NAME, 'label')
        for star in stars:
            try:
                etoile = star.find_element(By.TAG_NAME, 'svg')
                outer_html = etoile.get_attribute("outerHTML") or ""
                if ('fill-[#f5a623]' in outer_html or 'fill: #f5a623' in outer_html) and 'clip-path' not in outer_html:
                    filled += 1
                if '<clipPath id="StartHalfFilled_svg_a">' in outer_html or 'clip-path="url(#StartHalfFilled_svg_a)"' in outer_html:
                    half += 1
            except:
                continue
        return filled + (half * 0.5)
    except:
        return None


############################################-----PRODUCT HUNT-----################################################
def search_producthunt_no_cache(search_term: str):
    """
    Searches Product Hunt for products matching the given search term using Selenium and returns the results as a pandas DataFrame.
    This function uses a web scraper to navigate the Product Hunt website, extract product details, and compile them into a structured format. 
    It does not use caching, so each call will perform a fresh search.
    Args:
        search_term (str): The search term to query on Product Hunt.
    Returns:
        pandas.DataFrame: A DataFrame containing the following columns for each product:
            - title (str): The title of the product.
            - tagline (str): The tagline or short description of the product.
            - review (str): The review or feedback associated with the product.
            - rating (float or None): The star rating of the product, if available.
            - followers (str): The number of followers for the product, if available.
            - more_details (str): Additional details about the product.
    Notes:
        - This function requires the Selenium library and a compatible Chrome WebDriver to be installed.
        - The function may take a significant amount of time to execute depending on the number of products and network latency.
        - Ensure that the ChromeDriver version matches your installed Chrome browser version.
        - The function includes a series of try-except blocks to handle missing elements gracefully.
        - The function uses explicit waits and sleep calls to ensure elements are loaded before interacting with them.
    Raises:
        Exception: If there are issues with the web scraping process, such as element not found or navigation errors.
    Example:
        >>> df = search_producthunt_no_cache("AI tools")
        >>> print(df.head())
    """
    # Configurer Selenium
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")  # décommente pour exécuter sans interface
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)

    url = f"https://www.producthunt.com/search?q={search_term.replace(' ', '%20')}"
    driver.get(url)

    wait = WebDriverWait(driver, 10)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'main div.px-8.pb-8.sm\\:py-8')))
    time.sleep(10)

    results = []
    product_buttons = driver.find_elements(By.CSS_SELECTOR, 'main div.px-8.pb-8.sm\\:py-8 > div > button')

    for i in range(len(product_buttons)):
        try:
            product_buttons = driver.find_elements(By.CSS_SELECTOR, 'main div.px-8.pb-8.sm\\:py-8 > div > button')
            button = product_buttons[i]
            driver.execute_script("arguments[0].click();", button)
            time.sleep(8)

            try:
                followers = driver.find_element(By.CSS_SELECTOR, '#root-container > div.pt-header > div > main > section.flex.flex-col.gap-4.sm\\:flex-row.sm\\:items-center > div:nth-child(2) > span > p').text
            except:
                followers = "NONE"

            try:
                title = driver.find_element(By.CSS_SELECTOR, 'section.flex.flex-col.gap-4.sm\\:flex-row.sm\\:items-center > div:nth-child(2) > h1').text
            except:
                title = "NONE"

            try:
                tagline = driver.find_element(By.CSS_SELECTOR, '#root-container > div.pt-header > div > main > section.flex.flex-col.gap-4.sm\\:flex-row.sm\\:items-center > div:nth-child(2) > h2').text
            except:
                tagline = "NONE"

            try:
                review = driver.find_element(By.CSS_SELECTOR, 'section.flex.flex-col.gap-4.sm\\:flex-row.sm\\:items-center > div:nth-child(2) > span > a:nth-child(3)').text
            except:
                review = "NONE"

            try:
                stars_container = driver.find_element(By.CSS_SELECTOR, 'section.flex.flex-col.gap-4.sm\\:flex-row.sm\\:items-center > div:nth-child(2) > span > div.flex.flex-row')
                rating = stars(stars_container)
            except:
                rating = None

            try:
                more_details = driver.find_element(By.CSS_SELECTOR, 'section:nth-child(3) > div').text
            except:
                more_details = "NONE"

            results.append({
                "title": title,
                "tagline": tagline,
                "review": review,
                "rating": rating,
                "followers": followers,
                "more_details": more_details
            })

            driver.back()
            time.sleep(10)
        except Exception as e:
            print(f"Erreur produit {i}: {e}")
            driver.back()
            time.sleep(10)

    driver.quit()
    return pd.DataFrame(results)


def search_producthunt_cached(search_term, cache_dir="cache"):
    """
    Searches Product Hunt for products matching the given search term with caching support.

    This function retrieves a list of products from Product Hunt based on the given search term.
    It first checks if cached data is available for the search term. If not, it fetches fresh
    data using the search_producthunt_no_cache function and caches the result for future use.

    Args:
        search_term (str): The term to search for on Product Hunt.
        cache_dir (str, optional): The directory where cached files are stored. Defaults to "cache".

    Returns:
        pandas.DataFrame: A DataFrame containing the search results, either from the cache or freshly fetched.
    """
    return get_cached_or_fresh_data(search_term, search_producthunt_no_cache, cache_dir=cache_dir)

from google_play_scraper import reviews as gp_reviews

def get_reviews_by_app_id(app_id, lang='en', country='us', count=50):
    """
    Retrieves reviews for a specific app from the Google Play Store.

    Args:
        app_id (str): The unique identifier of the app on the Google Play Store.
        lang (str, optional): The language code for the reviews (default is 'en').
        country (str, optional): The country code for the reviews (default is 'us').
        count (int, optional): The number of reviews to retrieve (default is 50).

    Returns:
        list: A list of review texts for the specified app.
    """
    try:
        review_list, _ = gp_reviews(app_id, lang=lang, country=country, count=count)
        # Extract only the review content
        return [r["content"] for r in review_list if "content" in r]
    except Exception as e:
        print(f"Error retrieving reviews for {app_id}: {e}")
        return []


### 🧑‍💻 GitHub API
def search_github(search_term):
    """
    Searches for GitHub repositories based on a given search term.

    This function sends a GET request to the GitHub Search API to retrieve
    repositories matching the provided search term. The results are then
    processed and returned as a pandas DataFrame containing key details
    about each repository.

    Args:
        search_term (str): The term to search for in GitHub repositories.

    Returns:
        pandas.DataFrame: A DataFrame containing the following columns for each repository:
            - name (str): The name of the repository.
            - full_name (str): The full name of the repository (including the owner's username).
            - description (str): A brief description of the repository.
            - stars (int): The number of stars the repository has received.
            - language (str): The primary programming language used in the repository.
            - html_url (str): The URL to the repository on GitHub.

    Raises:
        requests.exceptions.RequestException: If there is an issue with the HTTP request.
        ValueError: If the response from the GitHub API cannot be parsed as JSON.
    """
    url = f"https://api.github.com/search/repositories?q={search_term}"
    headers = {"Accept": "application/vnd.github.v3+json"}
    response = requests.get(url, headers=headers)
    data = response.json().get("items", [])
    return pd.DataFrame([{
        "name": repo["name"],
        "full_name": repo["full_name"],
        "description": repo["description"],
        "stars": repo["stargazers_count"],
        "language": repo["language"],
        "html_url": repo["html_url"]
    } for repo in data])

def search_github_cached(search_term, cache_dir="cache"):
    """
    Searches for GitHub repositories based on a given search term with caching support.

    This function retrieves a list of GitHub repositories matching the search term.
    It first checks if cached data is available for the search term. If not, it fetches fresh
    data using the search_github function and caches the result for future use.

    Args:
        search_term (str): The term to search for in GitHub repositories.
        cache_dir (str, optional): The directory where cached files are stored. Defaults to "cache".

    Returns:
        pandas.DataFrame: A DataFrame containing the search results, either from the cache or freshly fetched.
    """
    return get_cached_or_fresh_data(search_term, search_github, cache_dir=cache_dir)









analyzer = SentimentIntensityAnalyzer()

def compute_sentiment_vader(review):
    """
    Computes the sentiment of a given review using the VADER sentiment analyzer.

    Args:
        review (str): The text of the review to analyze.

    Returns:
        str: The sentiment of the review, which can be "positive", "negative", or "neutral".
    """
    score = analyzer.polarity_scores(review)["compound"]
    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"

def compute_sentiments(reviews):
    """
    Computes the sentiment for a list of reviews.

    Args:
        reviews (list of str): A list of review texts to analyze.

    Returns:
        list of str: A list of sentiments corresponding to each review.
    """
    return [compute_sentiment_vader(r) for r in reviews]

def compute_sentiment_score(sentiments):
    """
    Computes the sentiment distribution as a percentage for a list of sentiments.

    Args:
        sentiments (list of str): A list of sentiments ("positive", "negative", "neutral").

    Returns:
        dict: A dictionary with the percentage distribution of each sentiment.
    """
    total = len(sentiments)
    counts = {"positive": 0, "negative": 0, "neutral": 0}
    for s in sentiments:
        counts[s] += 1
    return {k: round(v / total, 2) for k, v in counts.items()}
def convert_abbr_to_int(x):
    x = x.strip().replace("followers", "").replace(",", "").upper()
    if x.endswith('K'):
        return int(float(x[:-1]) * 1000)
    elif x.endswith('M'):
        return int(float(x[:-1]) * 1000000)
    elif x.endswith('B'):
        return int(float(x[:-1]) * 1000000000)
    else:
        try:
            return int(x)
        except ValueError:
            return None  # ou np.nan selon ton besoin



# Appliquer la fonction à la colonne